---
title: "Week4homework"
author: "Lambridge"
date: "2021/10/29"
output: html_document
---

# Ineqaulity task - week 4

## Reproduce 


### source data:
 HDI data from: http://hdr.undp.org/en/indicators/68606#
*Shapefile from: https://hub.arcgis.com/datasets/2b93b06dc0dc4e809d3c8db5cb96ba69_0/explore?location=-2.688200%2C0.000000%2C1.41



### package versions
```{r}
library(tidyverse)
library(sf)
library(here)
library(janitor)
library(countrycode)
library(tmap)
library(tmaptools)
```

###read the file

```{r}
HDI <- read_csv(here::here("data", "Gender Inequality Index (GII).csv"),
                locale = locale(encoding = "latin1"),
                na = "..")
World <- st_read(here::here("data", "World_Countries__Generalized_.shp"))
```
#select the columns and find the country code 

```{r}
HDIcols<- HDI %>%
  clean_names()%>%
  select(country, x2019, x2010)%>%
  mutate(difference=x2019-x2010)%>%
  slice(1:189,)%>%
  mutate(iso_code=countrycode(country, origin = 'country.name', destination = 'iso2c'))
```

# left-join

```{r}
Join_HDI <- World %>% 
  clean_names() %>%
  left_join(., 
            HDIcols,
            by = c("aff_iso" = "iso_code"))
```

# plot the map

```{r}
tmap_mode("plot")
qtm(Join_HDI,
    fill="difference")
```


